const RentalsData = [

    {
        city: "Gothenburg",
        address: "Linnégatan 22, 413 04 Gothenburg",
        type: "Villa",
        price_per_month: 25000,
        size_sqm: 120,
        rooms: 5,
        features: ["furnished: false", "balcony: true", "parking: true"],
        amenities: ["Garden", "Fireplace", "Garage", "Bathtub"],
        utilities: ["water_included: false", "electricity_included: false"],
        transport: ["bus_stop_distance_meters: 300", "train_station_distance_meters: 1000"],
        images: 'villa4.jpeg',
    },
    {
        city: "Stockholm",
        address: "Sveavägen 45, 113 59 Stockholm",
        type: "Apartment",
        price_per_month: 15000,
        size_sqm: 45,
        rooms: 2,
        features: ["furnished: true", "balcony: true", "parking: false"],
        amenities: ["WiFi", "Laundry", "Elevator", "Dishwasher"],
        utilities: ["water_included: true", "electricity_included: false"],
        transport: ["bus_stop_distance_meters: 100", "train_station_distance_meters: 500"],
        images: 'apartment3.jpeg',
    },
    {
        city: "Stockholm",
        address: "Birger Jarlsgatan 61, 114 56 Stockholm",
        type: "Studio",
        price_per_month: 12000,
        size_sqm: 35,
        rooms: 1,
        features: ["furnished: true", "balcony: false", "parking: false"],
        amenities: ["WiFi", "Laundry", "Elevator"],
        utilities: ["water_included: true", "electricity_included: true"],
        transport: ["bus_stop_distance_meters: 200", "train_station_distance_meters: 600"],
        images: "studio1.jpeg",
    },
    {
        city: "Gothenburg",
        address: "Kungsportsavenyen 22, 411 36 Gothenburg",
        type: "Apartment",
        price_per_month: 17000,
        size_sqm: 75,
        rooms: 3,
        features: ["furnished: true", "balcony: true", "parking: true"],
        amenities: ["WiFi", "Laundry", "Gym", "Pool"],
        utilities: ["water_included: true", "electricity_included: true"],
        transport: ["bus_stop_distance_meters: 100", "train_station_distance_meters: 500"],
        images: 'image3.jpeg',
    },
    {
        city: "Linköping",
        address: "Tullgårdsvägen 5, 582 54 Linköping",
        type: "Villa",
        price_per_month: 16000,
        size_sqm: 70,
        rooms: 3,
        features: ["furnished: true", "balcony: true", "parking: false"],
        amenities: ["WiFi", "Gym", "Laundry"],
        utilities: ["water_included: false", "electricity_included: true"],
        transport: ["bus_stop_distance_meters: 300", "train_station_distance_meters: 600"],
        images: 'villa3.jpeg',
    },
    {
        city: "Stockholm",
        address: "Norrmalmstorg 1, 111 46 Stockholm",
        type: "House",
        price_per_month: 30000,
        size_sqm: 100,
        rooms: 3,
        features: ["furnished: true", "balcony: true", "parking: true"],
        amenities: ["WiFi", "Laundry", "Air Conditioning", "Gym"],
        utilities: ["water_included: true", "electricity_included: true"],
        transport: ["bus_stop_distance_meters: 50", "train_station_distance_meters: 300"],
        images: 'house1.jpeg'
    },
    {
        city: "Stockholm",
        address: "Drottninggatan 12, 111 51 Stockholm",
        type: "Studio",
        price_per_month: 18000,
        size_sqm: 60,
        rooms: 2,
        features: ["furnished: true", "balcony: true", "parking: false"],
        amenities: ["WiFi", "Dishwasher", "Elevator"],
        utilities: ["water_included: true", "electricity_included: false"],
        transport: ["bus_stop_distance_meters: 150", "train_station_distance_meters: 400"],
        images:
            "studio4.jpeg",
    },
    {
        city: "Gothenburg",
        address: "Östra Hamngatan 15, 411 09 Gothenburg",
        type: "House",
        price_per_month: 21000,
        size_sqm: 95,
        rooms: 4,
        features: ["furnished: false", "balcony: true", "parking: true"],
        amenities: ["Garden", "Dishwasher", "WiFi"],
        utilities: ["water_included: true", "electricity_included: true"],
        transport: ["bus_stop_distance_meters: 200", "train_station_distance_meters: 800"],
        images: 'house2.jpeg',
    },

    {
        city: "Linköping",
        address: "Storgatan 15, 582 23 Linköping",
        type: "Apartment",
        price_per_month: 14000,
        size_sqm: 50,
        rooms: 2,
        features: ["furnished: true", "balcony: true", "parking: true"],
        amenities: ["WiFi", "Dishwasher", "Laundry"],
        utilities: ["water_included: true", "electricity_included: true"],
        transport: ["bus_stop_distance_meters: 150", "train_station_distance_meters: 700"],
        images: 'apartment1.jpeg',
    },
    {
        city: "Linköping",
        address: "Vasavägen 23, 582 77 Linköping",
        type: "Studio",
        price_per_month: 9500,
        size_sqm: 30,
        rooms: 1,
        features: ["furnished: true", "balcony: false", "parking: false"],
        amenities: ["WiFi", "Elevator"],
        utilities: ["water_included: true", "electricity_included: false"],
        transport: ["bus_stop_distance_meters: 100", "train_station_distance_meters: 400"],
        images: 'studio3.jpeg',
    },

    {
        city: "Helsingborg",
        address: "Kullagatan 32, 252 20 Helsingborg",
        type: "House",
        price_per_month: 19000,
        size_sqm: 110,
        rooms: 4,
        features: ["furnished: false", "balcony: true", "parking: true"],
        amenities: ["Garden", "Laundry", "Dishwasher", "WiFi"],
        utilities: ["water_included: false", "electricity_included: true"],
        transport: ["bus_stop_distance_meters: 250", "train_station_distance_meters: 1200"],
        images: 'house3.jpeg',
    },
    {
        city: "Helsingborg",
        address: "Bruksgatan 5, 252 24 Helsingborg",
        type: "Apartment",
        price_per_month: 13500,
        size_sqm: 55,
        rooms: 3,
        features: ["furnished: true", "balcony: true", "parking: false"],
        amenities: ["WiFi", "Laundry", "dishwasher"],
        utilities: ["water_included: true", "electricity_included: true"],
        transport: ["bus_stop_distance_meters: 150", "train_station_distance_meters: 500"],
        images: 'apartment4.jpeg',
    },
    {
        city: "Helsingborg",
        address: "Fasanvägen 9, 254 33 Helsingborg",
        type: "Studio",
        price_per_month: 7500,
        size_sqm: 25,
        rooms: 1,
        features: ["furnished: true", "balcony: false", "parking: false"],
        amenities: ["WiFi", "Elevator"],
        utilities: ["water_included: true", "electricity_included: false"],
        transport: ["bus_stop_distance_meters: 200", "train_station_distance_meters: 350"],
        images: 'studio5.jpeg',
    },

    {
        city: "Jönköping",
        address: "Östra Storgatan 25, 553 21 Jönköping",
        type: "Studio",
        price_per_month: 8500,
        size_sqm: 28,
        rooms: 1,
        features: ["furnished: true", "balcony: false", "parking: false"],
        amenities: ["WiFi", "Elevator"],
        utilities: ["water_included: true", "electricity_included: false"],
        transport: ["bus_stop_distance_meters: 100", "train_station_distance_meters: 400"],
        images: 'studio2.jpeg',
    },
    {
        city: "Jönköping",
        address: "Västra Storgatan 12, 553 24 Jönköping",
        type: "Apartment",
        price_per_month: 11000,
        size_sqm: 45,
        rooms: 2,
        features: ["furnished: true", "balcony: true", "parking: true"],
        amenities: ["WiFi", "Laundry", "Dishwasher"],
        utilities: ["water_included: true", "electricity_included: true"],
        transport: ["bus_stop_distance_meters: 120", "train_station_distance_meters: 500"],
        images: 'apartment5.jpeg',
    },
    {
        city: "Jönköping",
        address: "Södra Strandgatan 1, 553 20 Jönköping",
        type: "House",
        price_per_month: 20000,
        size_sqm: 90,
        rooms: 4,
        features: ["furnished: false", "balcony: true", "parking: true"],
        amenities: ["Garden", "WiFi"],
        utilities: ["water_included: false", "electricity_included: true"],
        transport: ["bus_stop_distance_meters: 150", "train_station_distance_meters: 600"],
        images: 'apartment6.jpeg',
    },

    {
        city: "Karlstad",
        address: "Drottninggatan 45, 652 25 Karlstad",
        type: "Apartment",
        price_per_month: 11000,
        size_sqm: 40,
        rooms: 2,
        features: ["furnished: true", "balcony: false", "parking: true"],
        amenities: ["WiFi", "Laundry", "Elevator"],
        utilities: ["water_included: true", "electricity_included: true"],
        transport: ["bus_stop_distance_meters: 150", "train_station_distance_meters: 600"],
        images: 'apartment7.jpeg',
    },
    {
        city: "Karlstad",
        address: "Storgatan 15, 652 26 Karlstad",
        type: "Villa",
        price_per_month: 23000,
        size_sqm: 130,
        rooms: 6,
        features: ["furnished: true", "balcony: true", "parking: true"],
        amenities: ["Garden", "Garage", "WiFi"],
        utilities: ["water_included: false", "electricity_included: false"],
        transport: ["bus_stop_distance_meters: 200", "train_station_distance_meters: 900"],
        images: 'villa5.jpeg'
    },
    {
        about: "About Stockholm Elites AB. Stockholm Elites AB was launched on Friday, March 15, 2013. Since then, we have been a prominent player in Stockholm rental market. Our partners have been successfully operating in the real estate and rental industry for over 20 years. Our long experience in the industry has meant that we have a broad and established customer base of companies, embassies and organizations that we help to broker housing for. We who work at Quality Living Stockholm are registered Rental Agents within SHRF (Swedish Rental and Relocation Association) and licensed by FMI (Real Estate Agents Inspectorate) and have a high level of expertise and experience in the rental market. We are a close knit team that cares about our clients and are always available to answer questions or clarify any doubts when it comes to Stockholms rental market and the rest of Sverige. If you are looking to rent out a home or rent a home, contact us or come by our office located at ChangeMaker 19 Hammarby in Stockholm",
        images: 'water.jpeg'
    },
]

export default RentalsData

export const cities = ['Home', ...new Set(RentalsData.map(rental => rental.type)), 'Contact', 'About'];




